# Generated by Django 2.0.4 on 2018-04-20 22:54

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='secret_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
