export const CHAT_ROOM_MESSAGE_RECEIVED = 'CHAT_ROOM_MESSAGE_RECEIVED'
export const CHAT_ROOM_USER_CONNECTED = 'CHAT_ROOM_USER_CONNECTED'
export const USER_SELECTED_CHAT_ROOM = 'USER_SELECTED_CHAT_ROOM'
export const CHAT_ROOM_ADD_MESSAGE = 'CHAT_ROOM_ADD_MESSAGE'
